sudo: required

services:
  - docker
  
env:
  - DOCKER_BUILD_DIR=alpine/3.2
  - DOCKER_BUILD_DIR=alpine/3.3
  - DOCKER_BUILD_DIR=alpine/edge
  - DOCKER_BUILD_DIR=busybox/latest
  
before_script:
  - cd $DOCKER_BUILD_DIR && docker build -t armtest .
  
script:
  - docker run -it armtest ":"
